---
- name: Get IP of the current node
  ansible.builtin.set_fact:
    tpa_single_node_rhel_host: "{{ ansible_ssh_host }}"

- name: Set a variable about RHEL
  ansible.builtin.set_fact:
    rhel: false

- name: Set a variable if is a RHEL as expected
  ansible.builtin.set_fact:
    rhel: true
  when:
    - ansible_facts['distribution'] == 'RedHat'
    - ansible_facts['distribution_major_version'] == '9'
    - (ansible_facts['distribution_version'] | split('.'))[1] | int >= 3

- name: Install Operating System Components
  ansible.builtin.include_tasks: os.yml
  when: rhel
  args:
    apply:
      become: true

- name: Execute Podman Actions
  ansible.builtin.include_tasks: podman.yml
  when: rhel
  args:
    apply:
      become: true
  vars:
    tpa_single_node_registry_username: "{{ lookup('env', 'TPA_SINGLE_NODE_REGISTRY_USERNAME') }}"
    tpa_single_node_registry_password: "{{ lookup('env', 'TPA_SINGLE_NODE_REGISTRY_PASSWORD') }}"

# 1 Configuring external services, DB, SSO
- name: Configure infra dependencies
  ansible.builtin.include_tasks: infra/main.yml
  args:
    apply:
      become: true
