- name: Trustification
  hosts: trustification
  vars:
    # V2.0.0
    tpa_single_node_trustification_image: registry.redhat.io/rhtpa/rhtpa-trustification-service-rhel:de73a7cd8373124f6a7a919d1d703cb53a24dc8e # noqa yaml[line-length]
  vars_files:
    - vars/main.yml
  tasks:
    - name: Include TPA single node
      ansible.builtin.include_role:
        name: tpa_single_node
