- name: Trustification
  hosts: trustification
  vars:
    # V2.0.0
    tpa_single_node_trustification_image: registry.redhat.io/rhtpa/rhtpa-trustification-service-rhel:c2dba10f946295576429c5a68d348b42ce5510fd # noqa yaml[line-length]
  vars_files:
    - vars/main.yml
  tasks:
    - name: Include TPA single node
      ansible.builtin.include_role:
        name: tpa_single_node
