---
- name: Generate OIDC secret manifest
  ansible.builtin.template:
    src: "{{ role_path }}/templates/manifests/infra/Secret-oidc.yaml.j2"
    dest: "{{ tpa_single_node_oidc_secret }}"
    mode: "0600"

- name: Apply storage secret manifest
  ansible.builtin.command:
    cmd: "podman kube play {{ tpa_single_node_oidc_secret }}"
  changed_when: false
